# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inv < Formula
  desc "A formatted investigation tool"
  homepage "https://github.com/dev01d/inv"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dev01d/inv/releases/download/1.1.0/inv_Darwin_x86_64.tar.gz"
      sha256 "34d840275586ec115232dd777c75a1b623e1de266b8b7c3412ea8af0ff34b14f"

      def install
        bin.install "inv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dev01d/inv/releases/download/1.1.0/inv_Darwin_arm64.tar.gz"
      sha256 "1ea3b42544a62970ff29f5d111307a749162389d6d3184af0be93008779c8ed9"

      def install
        bin.install "inv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dev01d/inv/releases/download/1.1.0/inv_Linux_x86_64.tar.gz"
      sha256 "4ab6d6e8893796a3a277e3c922004f9973cea53a15cbb1952e5e145fc34129a4"

      def install
        bin.install "inv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev01d/inv/releases/download/1.1.0/inv_Linux_arm64.tar.gz"
      sha256 "e6c7cb06935444b187806d4f07e8474ac73802f002078f61fe129b64c1e205da"

      def install
        bin.install "inv"
      end
    end
  end

  test do
    system "#{bin}/inv --version"
  end
end
