# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inv < Formula
  desc "A formatted investigation tool"
  homepage "https://github.com/dev01d/inv"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dev01d/inv/releases/download/0.1.0/inv_0.1.0_darwin_x86_64.tar.gz"
      sha256 "7cc4b09e47d081d594e1a47f36ff1e05161e4d0bf8abc329ab9279fa955b0769"
    end
    if Hardware::CPU.arm?
      url "https://github.com/dev01d/inv/releases/download/0.1.0/inv_0.1.0_darwin_arm64.tar.gz"
      sha256 "e29fa6877fef18cddf3920781f94e7420185353dd4906c670ea6208461b94a8a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dev01d/inv/releases/download/0.1.0/inv_0.1.0_linux_x86_64.tar.gz"
      sha256 "cc2644cbc461305b53f0cb805455d584c3fba1add1c0e90e487f791a297bf700"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev01d/inv/releases/download/0.1.0/inv_0.1.0_linux_arm64.tar.gz"
      sha256 "1a209ddeb606cf8762058f1ebb1583c3ec0858120ca54bc7d7ce53e8b8536e4b"
    end
  end

  def install
    bin.install "inv"
  end

  test do
    system "#{bin}/inv --version"
  end
end
